### ISSUE TITLE
Subscription with RSS feed 

### ISSUE THREAD

**Issue by chris-belcher** [bitcoinops/bitcoinops.github.io#109]
It would be nice if there bitcoinops could be subscribed to with an RSS feed as well as an email address.

Benefits: 

* RSS feed don't require the user to give out their email address (which could potentially be leaked and be flooded with spam). 

* Users may be more willing to subscribe if they feel its easier to unsubscribe (to unsubscribe from an RSS feed just remove the feed from your aggregator)

* Because RSS feeds are pull not push, they usually have much less spam. Which means users are much more likely to actually read them.

https://bitcoincore.org/ only offers an RSS feed, it doesn't offer email at all.

Many mail readers like Thunderbird already understand the RSS format, so the user experiance is actually very similar to email.

**Comment by bitschmidty** [comment]
Hey Chris, have you found/tried https://bitcoinops.org/feed.xml ? The link is hidden halfway down the homepage above "Member Companies".

**Comment by chris-belcher** [comment]
Oooh thanks. I didn't notice that.

**Comment by jnewbery** [comment]
Any website redesign PRs gratefully accepted :grin:
