### ISSUE TITLE
Stickying on r/bitcoin

### ISSUE THREAD

**Issue by chris-belcher** [bitcoinops/bitcoinops.github.io#116]
Hello everyone

The bitcoin subreddit mods try to sticky important and high-effort content roughly once a week. We'd like to sticky something about bitcoinops next. If you agree, then one of you should post a reddit thread linking to the page, then me or another mod will sticky it.

This has been done for projects like btcpayserver and it usually leads to much more traffic and interest.

It's good to use your reddit accounts because if people have comments or questions then you get a notification so you can answer. Naturally if trolls or spammers appear then they should be reported and the mods will deal with it.

**Comment by harding** [comment]
Hey @chris-belcher!  Thanks for the invitation!

Looking at our site, I realize we don't have any good overview information about the resources we provide.  Would it be an imposition on you and the other /r/bitcoin mods if we took a day or two to spruce up either our homepage or our about page?  Alternatively, we have some more exciting stuff in the pipeline (a chapter from our practical scaling techniques book we plan to publish next week about payment batching, and a comparison tool for scaling-related features between various wallets and services probably about a month out).

**Comment by chris-belcher** [comment]
That's ok, just tell me when you post the site.

Also with the same reddit account post a comment on your thread that briefly explains the site (could just copypaste here), because many reddit users don't seem to like leaving the reddit site and only ever read comments.

**Comment by harding** [comment]
@chris-belcher https://old.reddit.com/r/Bitcoin/comments/az90b4/bitcoin_optech_documentation_newsletters_and/

**Comment by harding** [comment]
Success!  (Suggest closing this issue now.)  Thanks, @chris-belcher!

![2019-03-11-13_58_45_334051838](https://user-images.githubusercontent.com/61096/54146239-ea6c4480-4405-11e9-90ff-e71c4407edb0.png)

**Comment by jnewbery** [comment]
Thanks for this, Chris!
