### ISSUE TITLE
Apple podcast link broken

### ISSUE THREAD

**Issue by realeinherjar** [bitcoinops/bitcoinops.github.io#1165]
Somehow for me the apple podcast link is broken.
To discard the possibility of a geoblock content, I've tried in severeal country locations using a VPN but to no avail.

**Comment by bitschmidty** [comment]
@realeinherjar thanks for bringing this up, I was able to fix the issue with the apple account/podcast. Can you try now? (Ill have to keep an eye on this as its not clear what caused the issue)

**Comment by realeinherjar** [comment]
Thanks. It works. I will keep an eye out for any new issues.
