### ISSUE TITLE
adjust logo size on home page

### ISSUE THREAD

**Issue by moneyball** [bitcoinops/bitcoinops.github.io#122]
From #120:

"I do think that in the future, as a separate PR, we can either (a) reduce the size of the Optech logo to better match the now-much-shorter text at the top of the home page or (b) add a bit more text description back before Learn More. But, there is so much goodness in this PR, that I think we should merge now. I'll file a separate Issue for my comment above, and we can discuss it there."

**Comment by jnewbery** [comment]
Concept ACK. Can you open an alternative to #120 with your proposed changes.

**Comment by moneyball** [comment]
Pull in remaining changes from #120 and address the large(ish) whitespace issue at the top of the home page.

Some options:
1. Reduce logo size
2. Add text "If you’re an engineer or manager at a Bitcoin company or an open source contributor and you’d like to be a part of this, please contact us at info@bitcoinops.org." after Learn More.
3. Add some other text?

@bitschmidty @harding suggestions?

**Comment by bitschmidty** [comment]
Voting option (b). My attempt.

"Bitcoin Optech is a not for profit organization helping Bitcoin users and businesses to integrate scaling technologies. 

We provide workshops, documentation, weekly newsletters, original research, case studies and announcements, and help facilitate improved relations between businesses and the open source community.

Learn more."

Here is how that would look.

<img width="903" alt="Screen Shot 2019-03-18 at 2 13 44 PM" src="https://user-images.githubusercontent.com/1615772/54557008-29f7db00-4988-11e9-89ff-a677b78fe7d8.png">

I think we can remove that "we provide..." sentence from about, or leave it if we want.

**Comment by moneyball** [comment]
This works for me.

**Comment by jnewbery** [comment]
Looks good to me. I'll update #120
