### ISSUE TITLE
Included articles not listed in topic mentions

### ISSUE THREAD

**Issue by vostrnad** [bitcoinops/bitcoinops.github.io#1270]
For example, [Bitcoin Optech Newsletter #264](https://bitcoinops.org/en/newsletters/2023/08/16/) includes (using `{% include}`) the article "Field Report: Implementing MuSig2" that links to [MuSig](https://bitcoinops.org/en/topics/musig/), but on the topic page of MuSig this mention isn't listed.

**Comment by bitschmidty** [comment]
@vostrnad I opened https://github.com/bitcoinops/bitcoinops.github.io/pull/1274 to address this example with the Musig2 field report. Are you aware of others?
