### ISSUE TITLE
JA: Miniscript blog post missing

### ISSUE THREAD

**Issue by bitschmidty** [bitcoinops/bitcoinops.github.io#1403]
@azuchi In https://github.com/bitcoinops/bitcoinops.github.io/pull/1396/files the article file and newsletter include worked correctly for the newsletter.

However, in my review, I missed that there was not an associated entry for the blog page.

For example, the MuSig field report translations previously:
https://github.com/bitcoinops/bitcoinops.github.io/pull/1245/files#diff-ff0890bd6342f683c5a397e0fb5e85cee943d0c02c6d67e6be959afafeccbeae

**Comment by azuchi** [comment]
@bitschmidty oh, I fogot it. I made a PR #1404 to add it. thanks!
