### ISSUE TITLE
Dashboard: Grafana data not populating in plots

### ISSUE THREAD

**Issue by dstadulis** [bitcoinops/bitcoinops.github.io#1459]
## expected behavior
When loading the dashboard's grafana page, relevant data is plotted

## observed behavior
No data from grafana is plotted on many or all of the pages

e.g.:
https://dashboard.bitcoinops.org/d/4Pm4uKFmk/fee-rate-comparison?orgId=1

**Comment by bitschmidty** [comment]
Similar issue to https://github.com/bitcoinops/btc-dashboard/issues/8
@dstadulis Were you seeking specific data? If so which.
