### ISSUE TITLE
Topic: data carrier transactions

### ISSUE THREAD

**Issue by GregTonoski** [bitcoinops/bitcoinops.github.io#1462]
Who can I contact to publish information about the data carrier transactions at https://bitcoinops.org/en/topics/ ?

**Comment by bitschmidty** [comment]
@GregTonoski Ive added your suggestion here: https://github.com/bitcoinops/bitcoinops.github.io/issues/721#issuecomment-1889791013

**Comment by GregTonoski** [comment]
Could I suggest content of the section/webpage, perhaps?

**Comment by murchandamus** [comment]
Given the contentious nature of the topic, it does not seem likely to me that we would be publishing any positional content on this topic beyond covering relevant debate of the topic
