### ISSUE TITLE
Add transcripts to exec briefing blog post [WAS: blog post: exec briefing]

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/bitcoinops.github.io#151]
Short blog post explaining what the exec briefing was, why we did it, and summaries of the three talks with links to the videos and slides available for download.

We can re-use the summaries from the newsletters and publish this after the 2019-06-12 newsletter.

I prefer to publish this on a different day from the newsletter so it doesn't get buried in the news.

**Comment by harding** [comment]
I think this is a good idea.

Separately, if I find time, I'd like to make transcripts.  How would that interact with this blog post?  E.g., would the transcripts be separate blog posts?  Would we just put them somewhere else on the site and link to them from the exec briefing blog posts?  Would we put them on Kanzure's website (if he's willing) and link to them there?  (Or are transcripts a bad idea?)

**Comment by jnewbery** [comment]
I like the idea of transcripts. I don't have any strong opinion about where they should go, and would certainly support them being on kanzure's website. He might even be willing to do the transcripts himself (@kanzure?)

**Comment by jnewbery** [comment]
Blog post is merged. We don't have transcripts yet. @harding - do you still think that's worthwhile? I'll leave this issue open with an updated title until we decide.

**Comment by harding** [comment]
> We don't have transcripts yet. @harding - do you still think that's worthwhile?

Probably not.  I suggest closing.  Thanks for checking!
