### ISSUE TITLE
RSS Feed duplicate "id" fields

### ISSUE THREAD

**Issue by bitschmidty** [bitcoinops/bitcoinops.github.io#155]
The RSS feed being generated is not generating unique id fields for each post entry. Each month has its own "id"s which each post of that month seems to get, instead of a unique id.

For example, for June 2019, all posts are getting this id:

`<id>/en/newsletters/2019/06/newsletter</id>`

Instead of the expected:

`<id>/en/newsletters/2019/06/05</id>`
`<id>/en/newsletters/2019/06/12</id>`

One example of how this manifests to a feed reader (newsblur), is that only one post per each month is shown in the feed:
<img width="392" alt="Screen Shot 2019-06-13 at 12 44 22 PM" src="https://user-images.githubusercontent.com/1615772/59455141-31891d80-8dd9-11e9-8f02-2461a7472b61.png">

**Comment by harding** [comment]
Looks like this is the line that may generate the id tag:

```
      <id>{{ post.id | absolute_url | xml_escape }}</id>
```

To see it in context, do `bundle show jekyll-feed` , then in the indicated directory, look at `lib/jekyll-feed/feed.xml`

Usually you can override jekyll plugins by creating a file in our source tree with the same file name.

I'd start debugging by seeing what the value of post.id is by printing that variable in a page, e.g. `{{post.id}}` on a preview site
