### ISSUE TITLE
For discussion: change newsletter publication date to Friday

### ISSUE THREAD

**Issue by harding** [bitcoinops/bitcoinops.github.io#1641]
| Current        | Proposed       | Activity |
|----------------|----------------|----------|
| SOD Fri UTC-10 | EOD Sun UTC-10 | Cut-off for additional news stories and merges (exception: security stuff) |
| EOD Sun UTC-10 | EOD Tue UTC-10 | Open PR |
| EOD Tue UTC-10 | EOD Thu UTC-10 | deadline for reviews, additional content, and edits |
| ~Noon Wed UTC  | ~Noon Fri UTC  | Publication |
| ~14:30 Thu UTC | TBD            | Podcast |

(EOD = End of Day; SOD = Start Of Day)

Main motivation: under the current schedule, I tend to put off writing
the newsletter until the weekend.  That worked fine when I was single
and weekends felt mostly like any other day to my work-at-home self.
Now I have a partner with a regular Mon-Fri job, so I want my weekends
free to spend with her.

Other advantages of this approach:

- At present, the podcast day conflicts with the #bitcoin-core-dev weekly
  meeting.  If we start publishing on Friday, the podcast will probably
  not be on Thursday any more.

Disadvantages:

- Change is annoying.

- Friday is supposed to be one of the worst times to publish things as
  some readers are already mentally checked out for the weekend.
  However, the podcast could be Monday morning U.S. Eastern Time, which
  might be a boost for it and could help bring attention back to the
  newsletter topics.

Please discuss!  I'm not in any rush to make changes, I'm not tied to
this particular proposed schedule, and I don't want to proceed unless all
regular contributors are onboard.

**Comment by ajtowns** [comment]
From a news perspective, publishing things on [friday](https://politicaldictionary.com/words/friday-news-dump/) is a good way to have them missed, isn't it? People are busy thinking about the weekend, leave early, or are in timezones where it's already the weekend. If you have a persistent reminder like an rss feed, that's fine; but if the newsletter scrolled past on twitter, you might just miss out.

Not sure what "EOD UTC-10" is exactly; I'm going to guess 6pm, so ~0400 UTC the next day, and SOD as 10h earlier. Skipping out the versions where publication would end up on a weekend:

| cutoff | open pr | comment deadline | publish | podcast | writing days | comment days |
|---|---|---|---|---|---|---|
| Fri 1800 | Mon 0400 | Wed 0400 | Wed 1200 | Thu 1430 | Fri, Sat, Sun |  Mon, Tue |
| Sat 1800 | Tue 0400 | Thu 0400 | Thu 1200 | Fri 1430 ? | Sat, Sun, Mon | Tue, Wed |
| Sun 1800 | Wed 0400 | Fri 0400 | Fri 1200 | Mon 1430 ? | Sun, Mon, Tue | Wed, Thu |
| Wed 1800 | Fri 0400 | Mon 0400 | Mon 1200 | Tue 1430 | Wed, Thu, Fri | Sat, Sun |
| Thu 1800 | Sat 0400 | Tue 0400 | Tue 1200 | Wed 1430 | Thu, Fri, Sat | Sun, Mon |

I'd probably go for "publish on monday" out of these, with a bit of extra time for comments, perhaps something like:

 * Cutoff for news: Tue 1800 UTC (SOD Tue UTC-10)
 * Open PR: Thu 2200 UTC (Noon Thu UTC-10)
 * Podcast invites: Fri 1200 UTC ?
 * Comment deadline: Mon 0400 UTC
 * Publish: Mon 1200 UTC
 * Podcast: Tue 1430 UTC

If that's not enough time for review/comments, push back to Tue publish/Wed podcast?

**Comment by harding** [comment]
@ajtowns's "publish on Monday" schedule works for me, but it does seem to imply everyone else will have to work on Friday or the weekend.

**Comment by LarryRuane** [comment]
> everyone else will have to work on Friday or the weekend

I don't mind at all.

**Comment by vostrnad** [comment]
I'm also fine with reviewing on weekends.

**Comment by murchandamus** [comment]
I’m in a similar situation as @harding and I generally try to avoid looking at work stuff on the weekend. I would probably not review the newsletter at all, if the review days were only on the weekend. On the other hand, I have already been contributing less to review recently due to other additional commitments I took on, so maybe my time-preference does not matter that much for the review days.

I would generally prefer if the Recap didn’t fall on Thursday, since we usually schedule NYC BitDevs on Thursdays, and therefore tend to have office guests more often on Thursdays.

**Comment by adamjonas** [comment]
Sounds like a useful experiment to run. FWIW I think readership matters, but I would prioritize sustainability above all other considerations. Given this newsletter's bus factor, I would support whatever Dave thinks is the best schedule for him.

**Comment by ajtowns** [comment]
"Friday noonish UTC" is Friday 10pm here, meaning it'll probably sit in my RSS feed until Monday anyway, so at least personally, it's the same thing :) If it were me, I'd still change "Publish Friday noonish" to "Publish Monday noonish" (keeping the other times the same) though. Moving the recap to the start of the week would be already a good win here too.

**Comment by harding** [comment]
> I'd still change "Publish Friday noonish" to "Publish Monday noonish" (keeping the other times the same) 

It feels like a disservice to our audience to have a completed newsletter, which might include timely information like security announcements, and to sit on it for a few days because we want more views from our least dedicated readers.

I think we should run the experiment to see whether there's a major difference between Friday and Monday (which, alas, does mean that we'll be delaying news for some of our readers on at least one occasion, making my previous argument a hypocritical).  If there's not a major difference, I think we should choose the schedule that's most convenient for us.  If there is a major difference, then we should discuss it further.

**Comment by ajtowns** [comment]
> It feels like a disservice to our audience to have a completed newsletter, which might include timely information like security announcements, and to sit on it for a few days because we want more views from our least dedicated readers.

If a vulnerability gets released the day after a newsletter is published, it'll still be a week before it's covered in the newsletter no matter what day it's published. Doesn't make sense to me to worry about a few days delay any which way for optech newsletters. (Likewise for if you spend a week or two reviewing a post before doing the optech write up; it's less timely, but the higher quality of the write up is much more valuable) If you want really timely updates, you should go to the source, not the weekly newsletter?

(Which is just to say (IMHO) that you shouldn't feel bad about it; not that you shouldn't release on friday if that makes you feel good!)

**Comment by murchandamus** [comment]
I think someone brought this up before, but if the newsletter is published on Friday, doing the recap on Monday would also draw additional attention to it. I would suspect that a lot of people track the newsletter via email or RSS, so it would land in their inbox either way. I support running the experiment, but my gut feeling is that Friday should work out fine.

**Comment by bitschmidty** [comment]
ACK on publishing on Friday.

In order to AB test the email list send times, Monday vs Friday, we would need to be collecting some tracking information (opens at least) from our email provider, Mailchimp.

I've manually been turning off that tracking for each individual weekly newsletter as Mailchimp doesnt have a global setting to turn it off. Due to the manual nature, Ive missed turning that off for some newsletters, but for this experiment, we would be deliberately leaving that collecting on. 

If we opt to collect email open rate information to facilitate this experiment, Id suggest we make a note of that on our disclaimer(s), perhaps: https://deploy-preview-1655--bitcoinops.netlify.app/en/newsletters/2024/05/15/#newsletter-publication-date-changes

Or if we think it would be helpful to have something broader on privacy policy, we can consider adding a page/text to the site.

**Comment by bitschmidty** [comment]
The first Friday publication went out today. I executed all of the same publishing steps (social media, etc) as normal with the exception of the email blast being a multivariate test this time. 

For this first week, I split delivery days 25% each to Friday/Saturday/Sunday/Monday. All (to be) sent at 630a ET. Both open and click tracking are enabled.

**Comment by bitschmidty** [comment]
## Week 1

| Segment    | Open Rate | Click Rate |
| -------- | ------- | ------- |
| Fri, May 17, 2024 6:30 AM  ET | 36.1%   | 2.8%
| Sat, May 18, 2024 6:30 AM  ET | 38.4%   | 2.1%
| Sun, May 19, 2024 6:30 AM  ET | 36.8%   | 2.3%
| Mon, May 20, 2024 6:30 AM  ET | 34.3%   | 2.2%

**Comment by harding** [comment]
@bitschmidty thanks!

Given that we also announced via Twitter and RSS on Friday, I suspect there's some confounding in those numbers, but if we simply take them at face value, I think they support publishing on whatever day is most convenient to us.

Friday continues to work for me, but I think Saturday morning publication might have the benefit of giving us a little extra time for reviews and additions.  Does anyone want to advocate either way?

Does anyone want further testing or to continue with the idea of trusting conventional wisdom about publishing on Monday?  ping @ajtowns 

This week's newsletter (see #1685) should be ready to go Friday (or Saturday), so I suggest we publish then unless a further test is suggested.

**Comment by ajtowns** [comment]
I support publishing on whatever day is most convenient for you :) I'd be a bit skeptical of drawing any conclusions from a single sample, particularly for a newsletter that was published only a couple of days after the previous newsletter, but if you're happy with friday/saturday I don't think you really need additional data to justify doing whatever feels best...

**Comment by bitschmidty** [comment]
I ran the 4 day email send time segmentation again this week. Though this time for 830a ET time slots. Stay tuned.

**Comment by bitschmidty** [comment]
## Week 2

| Segment    | Open Rate | Click Rate |
| -------- | ------- | ------- |
| Fri, May 24, 2024 8:30 AM  ET | 35.5%   | 2.1%
| Sat, May 25, 2024 8:30 AM  ET | 36.9%   | 2.5%
| Sun, May 26, 2024 8:30 AM  ET | 37.7%   | 1.9%
| Mon, May 27, 2024 8:30 AM  ET | 36.5%   | 2.3%

Open rate margin of error: +/- 1.7%
Click rate margin of error: +/- 0.7%

**Comment by bitschmidty** [comment]
I did not segment the email newsletter send times this week. I suspect data would be similar and dont see indications that deviating from sending Friday would garner audience benefits. Unless someone objects, I recommend we continue with Friday 1200 UTC publishing to everyone and Tuesday 1430 UTC for the Twitter Spaces Recap.

**Comment by harding** [comment]
> I recommend we continue with Friday 1200 UTC publishing to everyone and Tuesday 1430 UTC for the Twitter Spaces Recap.

Agreed.  Closing this issue, but continued discussion is welcome.  Thanks @bitschmidty for testing and everyone for you input!
