### ISSUE TITLE
tx size calculator 

### ISSUE THREAD

**Issue by ajtowns** [bitcoinops/bitcoinops.github.io#1656]
https://github.com/bitcoinops/bitcoinops.github.io/blob/a38d0dc17aa47a498f121be191987b477bbba2e6/en/tools/calc-size.md?plain=1#L19-L23

Unless I'm misunderstanding, I think this assumes signatures are 72 bytes, but they're usually 71 bytes due to https://github.com/bitcoin/bitcoin/pull/13666 and similar PRs in other software these days? At block 00000000000000000003478c6874f3901d7e1651e8e0a7b9291c49c1f571af6a I see 469 legacy sigs that are 71 bytes, and 148 thaat are 72 bytes (and 2 that are 70 bytes), fwiw.

See also https://github.com/bitcoinops/bitcoinops.github.io/pull/322#issuecomment-583685976

**Comment by murchandamus** [comment]
I have in the past always calculated with the maximum, as people building a transaction at minFeerate will get a non-standard transaction if they are short one sat.

**Comment by bitschmidty** [comment]
I dont have a preference on the approach here. @ajtowns thoughts on @murchandamus "worst case" approach?

**Comment by ajtowns** [comment]
"worst case" for bitcoin core is 71 bytes -- you only get 72 bytes if you're also using older software that doesn't do low-R grinding. Not sure what's best -- I was using it to predict what core txs would look like and was confused at the discrepency; if others are using it to estimate a tx size in order to manually calculate fees to plug in to wallets that don't do low-R grinding, being more conservative might make sense.

The page currently says:

> ecdsa_signature (72) (about half of all signatures generated with a random nonce are this size, about half are one byte smaller, and a small percentage are smaller than that)

which describes the behaviour prior to low-R grinding; with low-R grinding, 255/256 signatures are 71 bytes, and 1/256 are 70 bytes, give or take. So updating that text might be worthwhile if nothing else?

**Comment by murchandamus** [comment]
It would make sense to mention that wallets using low-R grinding would expect smaller signatures. Only about a quarter of signatures are produced with low-R grinding, so continuing to show the conservative value seems like the right move overall:

![image](https://github.com/user-attachments/assets/51215fab-ef65-40b3-ae07-a2a57ce80edd)

via: https://transactionfee.info/charts/bitcoin-script-ecdsa-rs-values/

**Comment by bitschmidty** [comment]
> It would make sense to mention that wallets using low-R grinding would expect smaller signatures

Seems like a reasonable compromise on this issue. @murchandamus if youre up for it, I think a wording change or addition somewhere on the page would address this?

**Comment by murchandamus** [comment]
I threw something together here: https://github.com/bitcoinops/bitcoinops.github.io/pull/2023
