### ISSUE TITLE
Add 'call to action' to website

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/bitcoinops.github.io#17]
@moneyball - you said you'd take this one in yesterday's call. Ping me if you need any help with Jekyll.

**Comment by moneyball** [comment]
[] Create verbage for member companies
[] Determine layout/location of member company call to action, with an eye toward listing existing members in the future
[] Create verbage for individuals getting involved
[] Determine layout/location of individual call to action

**Comment by moneyball** [comment]
#29 addressed this
