### ISSUE TITLE
Style guide updates

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/bitcoinops.github.io#171]
Please comment on this issue if you have suggestions for the Optech style guide. I'll update a list in this issue description as we go and then merge all agreed changes in one PR/commit.

**Comment by harding** [comment]
- [ ] multiparty not ~~multi-party~~ (I've been a bit inconsistent about this, but git grep says we currently have 17 multiparty versus 3 multi-party)

**Comment by harding** [comment]
Do we need to say anything in the guide about sighashes?  IMO, I don't think that should be a unintroduced abbreviation (we've always introduced "signature hash" -> "sighash" in the past, I think) and I don't think we need to put anything in the guide about, e.g., `SIGHASH_ALL` since that's the actual technical term and not an abbreviation.  However, I don't know how y'all feel about it.

**Comment by jnewbery** [comment]
I agree that sighash should be introduced, and that we don't need to say anything about technical terms like `SIGHASH_ALL`

**Comment by harding** [comment]
- [ ] coinjoin as a common noun (not ~~Coinjoin~~) and with no intra-word capitals (~~coinJoin~~) or hyphen (~~coin-join~~)

**Comment by jnewbery** [comment]
- [x] sybil attack (common noun), not Sybil attack (proper noun)

**Comment by harding** [comment]
- [ ] BIPXXX referencing a specific BIP number (no zero padding)

Just adding the parenthetical text above to the existing text in the document.

**Comment by harding** [comment]
- [ ] preimage (not ~pre-image~).  I've been inconsistent on this in the Optech repository but preimage is the current majority according to a quick git grep.

**Comment by bitschmidty** [comment]
- [ ] softfork not soft fork
- [ ] hardfork not hard fork

**Comment by harding** [comment]
@bitschmidty that's a good one for the style guide, but I'd prefer the spaced versions (which are also currently overwhelmingly used in the repo at present per git grep).

**Comment by bitschmidty** [comment]
I happened to see the softfork title in Steves presentation and also in the bitcoin wiki. I dont have a preference either way. Ill see if others opine.

**Comment by jnewbery** [comment]
No strong preference either way between 'softfork'/'hardfork' and 'soft fork'/'hard fork', so I suggest we go with spaced versions, since that's what's been used in newsletters so far.

**Comment by bitschmidty** [comment]
- [ ] MuSig not musig, Musig, or muSig

**Comment by harding** [comment]
- [ ] single-sig not ~singlesig~ (this seems inconsistent with multisig, but I think it's ok.  Multisig is a common term in Bitcoin, whereas single-sig is something less often said.

**Comment by harding** [comment]
@jonatack noted elsewhere that "MuSig" looks odd in a list of other technologies we've lowercased, e.g. "schnorr, taproot, MuSig, bloom filters, merkle trees"

**Comment by harding** [comment]
- [ ] True and False capitalized when referring to bool arguments in plain text, e.g. "set foo to True".  When used in code, use whatever capitalization is technically appropriate, e.g. "set `foo=true`"

**Comment by jnewbery** [comment]
> "MuSig" looks odd in a list of other technologies we've lowercased, e.g. "schnorr, taproot, MuSig, bloom filters, merkle trees"

I think this is fine, since MuSig is not widely known or implemented. I imagine if it becomes popular it'll evolve to musig over time.

> True and False capitalized when referring to bool arguments in plain text...

Different languages have different conventions. C/C++ doesn't capitalize boolean literals, and Python does. I don't have a strong preference either way. I'm curious why you prefer capitalized?

I plan to open a PR to merge all of the updates into our style guide this week.

**Comment by harding** [comment]
@jnewbery 

>  I'm curious why you prefer capitalized [boolean literals in regular text]?

To distinguish them from the words "true" or "false" without having to use italics or something else.  If you're not a fan, I'm happy to drop that suggestion.

**Comment by harding** [comment]
- [ ] Script for Bitcoin Script is capitalized when referring to the language, but lowercase when referring to an individual script.

**Comment by harding** [comment]
Partially Signed Bitcoin Transaction not ~~Partially-Signed Bitcoin Transaction~~.  We may not need to put this in the guide as (1) grammar rules [say](https://www.grammarbook.com/punctuation/hyphens.asp) not to hyphenate and (2) a quick web search for "Partially-Signed Bitcoin Transactions" seems to show I'm the only one getting it wrong.

h/t @jonatack

**Comment by jnewbery** [comment]
> Partially Signed Bitcoin Transaction not ~Partially-Signed Bitcoin Transaction~. We may not need to put this in the guide

Thanks for noting this here. I agree that we don't need to include this in the style guide.

**Comment by harding** [comment]
Should Eltoo be uppercase (like MuSig) or lowercase (like taproot)?  I've no preference, but it's a topic for this upcoming week's newsletter, so let me know what y'all prefer!

**Comment by jnewbery** [comment]
I have no preference between Eltoo and eltoo.

**Comment by harding** [comment]
Preferred terms:

| Use | Don't use | Notes |
|-|-|-|
| Merklized Alternative Script Trees (MAST) | Merklized Abstract Syntax Trees (MAST) | May want to link to: <https://bitcoinops.org/en/newsletters/2018/12/28/#fn:fn-mast> |

Note, I've also added a note to the MAST topic for the upcoming topic index which I think will be the better link if it gets merged.

**Comment by jonatack** [comment]
AFAIK the authors of eltoo [originally wrote it lowercase](https://blockstream.com/eltoo.pdf) and it seems good that way.

Between "merklized", "merkleized", and "merkelized" I thought the latter spelling was correct. Convert the word to an "ation" sort of noun: "merkelization" is arguably the one that can. Googling them gave me roughly three times more results for "merkelized" as well -- granted, that doesn't mean it's correct. I like "merkelisation" too :smile_cat:

**Comment by jonatack** [comment]
Oh, just saw your link to AJ in the mailing list:
```
[0] (I think I'm going to claim "MAST" stands for "merkelized alternative
     script tree" these days, since they're not "abstract syntax trees")
```

**Comment by harding** [comment]
@jonatack I get a 3:4 ratio when I search Google (did you remember to use quotes?):

https://www.google.com/search?q=%22merklized%22
https://www.google.com/search?q=%22merkelized%22

In any case, I just emailed Ralph Merkle to ask if he has a preference.  If he does and it's sensible, I propose we use that.

**Comment by harding** [comment]
```
My name is Merkle, not Merkel, so my preference is "merklized".

Please feel free to share.

Ralph C. Merkle
```

**Comment by jonatack** [comment]
@harding :+1: I omitted the quotes, and above all, omitted remembering the name Merkle!

"Merkle-ized" seems most respectful of the name, but who's to quibble with Ralph Merkle himself :shipit:

**Comment by harding** [comment]
- [ ] Spelling: "adaptor signatures" rather than ~~"adapter signatures"~~.  Rationale: that's how Andrew Poelstra spells it:

![2019-09-14-11_39_35_077299037](https://user-images.githubusercontent.com/61096/64913901-6b253980-d6e4-11e9-92c6-8de2776411f0.png)

**Comment by harding** [comment]
- [ ] Spelling: feerate (one word) not ~~fee rate~~ (two words)

**Comment by jnewbery** [comment]
- [ ] _secp256k1_ not _Secp256k1_ or _SECP256k1_ or _SECP256K1_

**Comment by bitschmidty** [comment]
I see we use both proof of work vs proof-of-work. Context dependent?

**Comment by jonatack** [comment]
> ```
> My name is Merkle, not Merkel, so my preference is "merklized".
> 
> Please feel free to share.
> 
> Ralph C. Merkle
> ```

Should "Merkle" be used rather than "merkle" for the noun?

**Comment by harding** [comment]
@bitschmidty `git grep proof-of-works` says we've been pretty good about only use "proof-of-work" as an adjective phrase (with one exception).

@jonatack I try to avoid lots of special case rules, so I think we should generally try to treat eponyms as common nouns, e.g. "merkle root" or "schnorr signature".

**Comment by bitschmidty** [comment]
> git grep proof-of-works says we've been pretty good about only use "proof-of-work" as an adjective phrase (with one exception).

is there value in codifying this usage in the guide?

**Comment by harding** [comment]
@bitschmidty sure!

- [ ] Do not hyphenate "proof of work" when used as a noun (e.g. "Bitcoin uses proof of work") but do hyphenate when used as an adjective phrase (e.g. "Bitcoin's proof-of-work security is economic in nature").

**Comment by harding** [comment]
- [ ] *Generation transaction* not ~~coinbase transaction~~

This is my personal preference since the company Coinbase made the term "coinbase transaction" confusing.  Although it's a bit hard to tell because of conflation, I appear to be on the less popular side of this divide, per the StackExchange:

- 929 results for coinbase transaction: https://bitcoin.stackexchange.com/search?q=coinbase+transaction
- 226 for generation transaction: https://bitcoin.stackexchange.com/search?q=generation+transaction

So I'm willing to go with "coinbase transaction" in the style guide if any of you would prefer that.

**Comment by jnewbery** [comment]
I prefer coinbase transaction over generation transaction.

**Comment by harding** [comment]
> I prefer coinbase transaction over generation transaction.

You're wrong and a terrible human being for preferring that, but I updated my suggestion accordingly.

**Comment by bitschmidty** [comment]
OP_RETURN vs op_return op return. More generally always capitalize opcode words.

**Comment by jonatack** [comment]
I prefer coinbase transaction as well, but it's unfortunate that many people may initially be confused as to whether it refers to the exchange that named itself the same.

**Comment by harding** [comment]
- [ ] *sigop* not ~~SigOp~~  This is an abbreviation that we should introduce, but I don't think it's necessary to upper camel case it.  See @jonatack comment here: https://github.com/bitcoinops/bitcoinops.github.io/pull/227#discussion_r327489006

**Comment by bitschmidty** [comment]
We specify k-of-n in the style guide already. But what about n-of-n? Is there even an alternative that people use for n-of-n?

**Comment by jnewbery** [comment]
> Is there even an alternative that people use for n-of-n?

I don't think I've ever come across an alternative to n-of-n, but we can include it in the style guide for completeness.

**Comment by jnewbery** [comment]
> OP_RETURN vs op_return op return. More generally always capitalize opcode words.

- [x] Added. I've also added that we should refer to opcodes as opcodes (not Opcodes or OpCodes or OPCODES)

**Comment by jnewbery** [comment]
Latest changes merged in https://github.com/bitcoinops/bitcoinops.github.io/pull/252

**Comment by harding** [comment]
- [ ] *Bitcoin invoice address* or *invoice* instead of ~~Bitcoin address~~ or ~~address~~, as per the recently-added [BIP179](https://github.com/bitcoin/bips/blob/master/bip-0179.mediawiki)

**Comment by jnewbery** [comment]
Let's track whether we want to adopt _bitcoin invoice address_ in a separate issue: #265 .

**Comment by in3rsha** [comment]
What's the recommended way to refer to the two different byte orders used in Bitcoin?

For example, when you search for a block you use:

    000000000002d01c1fccc21636b607dfd930d31d01c3a62104612a1719011250

But when you refer to this block hash when constructing a raw block header you put it in this byte order:

    50120119172a610421a6c3011dd330d9df07b63616c2cc1f1cd0020000000000

There seem to be a few different terms to describe these byte orders:

* Big Endian / Reverse Byte Order / Network Byte Order
*  Little Endian / Internal Byte Order 

Which terms are best to use?

**Comment by jonatack** [comment]
> What's the recommended way to refer to the two different byte orders used in Bitcoin?

So far I've mostly seen big-endian and little-endian.

**Comment by harding** [comment]
@in3rsha ooh, that's a good one!  I prefer *internal byte order* and *RPC byte order* per [this documentation](https://btcinformation.org/en/developer-reference#hash-byte-order) written as a result of [this discussion](https://github.com/bitcoin-dot-org/bitcoin.org/issues/580).  I particular, I think Sergio Lerner makes a good case [here](https://github.com/bitcoin-dot-org/bitcoin.org/issues/580#issuecomment-57158555) that hashes don't have endianess---they're represented identically on every platform.  (Sure, there's one context where Bitcoin uses a hash as a number, but even though that number can be big endian or little endian, the hash it was derived from was just a byte array.)

**Comment by in3rsha** [comment]
@harding Thanks for the helpful reply and links. That answers a lot of questions.

**Comment by in3rsha** [comment]
> @in3rsha ooh, that's a good one! I prefer _internal byte order_ and _RPC byte order_ per [this documentation](https://btcinformation.org/en/developer-reference#hash-byte-order) written as a result of [this discussion](https://github.com/bitcoin-dot-org/bitcoin.org/issues/580). I particular, I think Sergio Lerner makes a good case [here](https://github.com/bitcoin-dot-org/bitcoin.org/issues/580#issuecomment-57158555) that hashes don't have endianess---they're represented identically on every platform. (Sure, there's one context where Bitcoin uses a hash as a number, but even though that number can be big endian or little endian, the hash it was derived from was just a byte array.)

Would it be fair to say that when talking about hashes (e.g. transaction hashes and block hashes), it's best to describe them based on being either in _internal byte order_ or _RPC byte order_.

However, when it comes to other fields inside serialized transaction data, they are in fact in _little-endian_ (e.g. the version in a block header is `01000000`, which is 1 in little-endian).

Therefore, little-endian is the typical _internal byte order_ for serialized data, and this same term has been used to describe transaction hashes and block hashes, even though they typically do not have an "endianness"?

**Comment by harding** [comment]
@in3rsha sorry, I don't understand your question.

**Comment by in3rsha** [comment]
> @in3rsha sorry, I don't understand your question.

Would it be correct to describe other field inside serialized data as being in little-endian?

However, it's more accurate to describe hashes inside serialized data as being in "internal byte order", as hashes do not have an endianness?

**Comment by harding** [comment]
In the block header, nVersion, nTime, and the mantissa of nBits are little-endian.  PrevBlock, MerkleRoot, and Nonce aren't numbers, so I don't think they have endianess.  I think most other numbers in the protocol are little-endian, with some exceptions like IP addresses (which IIRC are always big endian in Bitcoin's P2P protocol).

I think "internal byte order" is more accurate for hash digests.

**Comment by harding** [comment]
- [ ] *uneconomical output* instead of ~~dust~~, but still use *dust limit*.  Rationale: people confuse "dust" with the "dust limit".  Dust (uneconomical outputs) are UTXOs that cost more to spend then they add in value to a transaction, so nobody would normally spend them.  The dust limit is the minimum value an output must contain in order for Bitcoin Core to relay a transaction containing that output.  What's economical or not changes as minimum feerates change, but the dust limit doesn't change often.

**Comment by harding** [comment]
- [ ] Unintroduced abbreviations: LND for Lightning Network Daemon.  (I'd half forgotten this was even an abbreviation!)
- [ ] Unintroduced abbreviations: RPC for Remote Procedure Call
- [ ] Nitpick: in "don't use" columns, replace multiple "or" statements with commas and a final "or", e.g. `OPCODE or OpCode or Opcode or op code` → `OPCODE, OpCode, Opcode, or op code`
- [ ] Nitpick: "MuSig" should probably be moved from *Compound words* to *Proper nouns*.  "Mu" is a phoneme rather than an English word, so I don't think MuSig is a compound word (even µSig wouldn't be a compound word IMO, though microsig would).  Also, it seems to me that the main reason it's in the list is that we've decided to always capitalize it despite lowercasing most other special terms.

**Comment by jnewbery** [comment]
#273 resolves all the points made by @harding here: https://github.com/bitcoinops/bitcoinops.github.io/issues/171#issuecomment-554149009 and here: https://github.com/bitcoinops/bitcoinops.github.io/issues/171#issuecomment-557139252. I haven't added anything about 'internal byte order' since I don't know the exact wording that we'd want to use. @harding - if you think we should have something in the style guide for that, can you add a commit to #273?

Since style guide changes have slowed down, I'm going to close this issue. We can open PRs for any further changes to the style guide.

**Comment by sipa** [comment]
Just stumbled upon this... I find it very strange to not capitalize "Schnorr", "Merkle", "Sybil" -- they're literally people's names. I understand not doing that for derived terms like "merklized" or "chaumian", but when the name itself is used it just looks weird to me. It seems Wikipedia also capitalizes such uses.

**Comment by harding** [comment]
@sipa the problem with the capitalization of eponyms is that it's inconsistent ([amusingly so sometimes](https://archive.seattletimes.com/archive/?date=19961013&slug=2353931)).  At some point, different for each word and which dictionary you consult, the eponym goes from a capitalized proper noun to a common noun without special capitalization.  Although it's not recommended by any style guide I've read, I gave up on consulting dictionaries and trying to guess current capitialization trends and just decided to treat all eponyms as common nouns, as much as I can get away with it.

Beyond simplifying writing and editing, the elimination of unnecessary capitalization may have some other minor benefits, such as speeding up the ability to skim a paragraph.  The only downside I can think of is that it may not pay sufficient respect to the people the eponyms refer to, but I think simply using their name as part of a term is already a pretty significant homage.

**Comment by jnewbery** [comment]
Our style guide is to ensure we have consistent usage across our newsletters and other materials. We don't prescribe that other people follow them, but of course they're welcome to if they find them useful. Some may find our customs unusual or even eccentric, but they serve us well.

> "Schnorr", "Merkle", "Sybil" -- they're literally people's names

I'll grant you one out of three here. "Schnorr" and "Merkle" are _actually_ people's names, but only "Sybil" is _literally_ someone's name, and that someone's actual name was [Shirley Ardell Mason](https://en.wikipedia.org/wiki/Shirley_Ardell_Mason). The English language has many fictional eponyms, including yahoo, gargantuan, milquetoast and polyanna. These words are often not capitalized. Sybil is one such fictional eponym, and we choose to not capitalize it.

As for schnorr signatures and merkle trees, you're right that eponyms of real people are often capitalized as nouns. However, there are many counter-examples. You might boycott our lowercase use of schnorr, but you probably wouldn't [Boycott](https://en.wikipedia.org/wiki/Charles_Boycott) it. You might eat a sandwich while driving a diesel car, but probably not a [Sandwich](https://en.wikipedia.org/wiki/John_Montagu,_4th_Earl_of_Sandwich) while driving a [Diesel](https://en.wikipedia.org/wiki/Rudolf_Diesel) car. You might call the schnorr signature method an algorithm and probably not an [Algorithm](https://en.wikipedia.org/wiki/Muhammad_ibn_Musa_al-Khwarizmi).

At the end of the day, this is a question of style. Ours is to lowercase all eponyms that have become sufficiently widely used.

**Comment by sipa** [comment]
> You might boycott our lowercase use of schnorr, but you probably wouldn't Boycott it. You might eat a sandwich while driving a diesel car, but probably not a Sandwich while driving a Diesel car. You might call the schnorr signature method an algorithm and probably not an Algorithm.

I'm aware that there are lots of common English words that originated as proper names, but my understanding is that in common usage, these are for things that are *far* more common than any of the examples here. For example, https://www.e-education.psu.edu/styleforstudents/c2_p11.html says:

> Note: The only way to be sure if a word derived from a person’s name should be capitalized is to look it up in the dictionary. For example, "Bunsen burner" (after Robert Bunsen) is capitalized, while "diesel engine" (after Rudolph Diesel) is not.

If "Bunsen burner" is capitalized in anything close to common style, I'd say none of the examples here are remotely close to common enough to warrant being non-capitalized.

> At the end of the day, this is a question of style. Ours is to lowercase all eponyms that have become sufficiently widely used.

Of course, style is just that. I just wanted to point out I think it's a weird one. Apparently you have your reasons for the choices you made, and that's fine.
