### ISSUE TITLE
A potential typo in Newsletter-306

### ISSUE THREAD

**Issue by hulatown** [bitcoinops/bitcoinops.github.io#1738]
https://github.com/bitcoinops/bitcoinops.github.io/blob/f5bc1191f904df00c17f0e86fc6c292dc292acf0/_posts/en/newsletters/2024-06-07-newsletter.md?plain=1#L227C54-L227C58

Is the "HKDK" here a typo, which should be "HKDF"?

**Comment by bitschmidty** [comment]
Looks like youre right it should be HKDF

**Comment by hulatown** [comment]
Got it! Fixed it in the Chinese version
