### ISSUE TITLE
RGB v0.11-beta 8

### ISSUE THREAD

**Issue by UkolovaOlga** [bitcoinops/bitcoinops.github.io#1879]
You missed a very big and important RGB release. Please kindly add it to your newsletters (weekly and Monthly) and to the 'Client-side validation' Topic on the website.
https://rgb.tech/blog/release-v0-11-beta-8/
Thanks
@harding

**Comment by bitschmidty** [comment]
Thanks, Ill add this for consideration in our monthly client and services segment later in the month.

**Comment by UkolovaOlga** [comment]
@bitschmidty With all due respect, I think there is a misunderstanding here. The release I mentioned has nothing to do with 'client and services' section of the newsletter as it's neither a 'client' nor a 'service'. Client-side validation is NOT the same as client-server development paradigm in classical programming, which actually @harding explains for everyone, to somewhat acceptable extent, on your website https://bitcoinops.org/en/topics/client-side-validation/ @harding put effort into creating that page, so maybe reading it every now and then would actually benefit everyone.

Coming back to the initial topic of the issue. The release I mentioned before, goes into the Notable releases and News sections and, again - into the main topic, which you generously called Client-side validation. I uderstand that you are busy, so I made the request very simple and sent you all the links and explained the details. Glad to be of help.

You will have a lot of informational inflow into the 'clients and service' section too as there are over 6 projects and even more products being updated. So I would advise to save the space for relevant content.

**Comment by bitschmidty** [comment]
RGB is a client application that uses the bitcoin blockchain. If you'd prefer we dont consider covering RGB releases in that monthly segment moving forward, let me know.

**Comment by bitschmidty** [comment]
@UkolovaOlga I am looking at the RGB v0.11 Beta 8 release page. It looks like there is change to the nonce data type, and a change to data persistence. Let me know if I have missed anything else. If that is the case, I dont think this beta 8 is something we will cover in the client/services segment this month.

**Comment by UkolovaOlga** [comment]
> RGB is a client application that uses the bitcoin blockchain. If you'd prefer we dont consider covering RGB releases in that monthly segment moving forward, let me know.

RGB is not a client application, which was pointed out before, at least twice, and is even written in your own Bitcoin Optech resource. If you call RGB a client application, then I guess Liquid, tapAss and Lightning are client applications too, by the same logic?

**Comment by UkolovaOlga** [comment]
> @UkolovaOlga I am looking at the RGB v0.11 Beta 8 release page. It looks like there is change to the nonce data type, and a change to data persistence. Let me know if I have missed anything else. If that is the case, I dont think this beta 8 is something we will cover in the client/services segment this month.

I already mentioned the sections where RGB should be going. It is NOT a client-application thing and never has been.  
Also - taking into account that over the past 2 years you haven't published anything from our progress, there is much more that was changed than 'nonce data type and a change to data persistance'. There is a lot of information present in the release description, feel free to get acquainted with them and ask questions.

You attempts to boycott publishing any updates on RGB or any other technology from our tech stack and leading the conversation into an off-topic direction by misinterpreting what RGB and client-side validation is, is a weird approach to receive from the team that, supposedly, is about covering best development efforts in the space. Mind telling what the goal of Bitcoin Optech is? Maybe I misunderstood something and the only thing you're focusing on is Bitcoin Core releases (which you announce before they even happen) https://x.com/dr_ukolova/status/1842570764303610118

**Comment by vostrnad** [comment]
> (which you announce before they even happen)

Bitcoin Core 28.0 was most certainly released before its announcement in the newsletter. See https://github.com/bitcoinops/bitcoinops.github.io/pull/1929#discussion_r1787243104 where I notified Optech editors of the release.

**Comment by UkolovaOlga** [comment]
> > (which you announce before they even happen)
> 
> Bitcoin Core 28.0 was most certainly released before its announcement in the newsletter. See [#1929 (comment)](https://github.com/bitcoinops/bitcoinops.github.io/pull/1929#discussion_r1787243104) where I notified Optech editors of the release.

We and all our progress have been denied mentions for less than being a release candidate or not having the release properly packed on Github according to the maintainers' procedure. For us - we always violate some rules. For Bitcoin core - even a RC is a release regardless them violating their own release procedures (and Optech - violating theirs).
