### ISSUE TITLE
Add RGB v0.11-beta 8 tо notable releases, news section and Client-side validation topic page

### ISSUE THREAD

**Issue by UkolovaOlga** [bitcoinops/bitcoinops.github.io#1886]
Link to the topic page https://bitcoinops.org/en/topics/client-side-validation/
Link to the previous issue, which was definitely closed and marked as 'complete' by mistake due to a misunderstanding of what a client-side validation is https://github.com/bitcoinops/bitcoinops.github.io/issues/1879

@harding please check this and provide the feedback

**Comment by bitschmidty** [comment]
Id imagine if there is a substantial RGB release that is covered in the client / services section, we would then link to it in the client side validation page, just as we did with the taproot assets release recently: https://bitcoinops.org/en/topics/client-side-validation/#optech-newsletter-and-website-mentions

**Comment by UkolovaOlga** [comment]
> Id imagine if there is a substantial RGB release that is covered in the client / services section, we would then link to it in the client side validation page, just as we did with the taproot assets release recently: https://bitcoinops.org/en/topics/client-side-validation/#optech-newsletter-and-website-mentions

As far as I'm aware of the process, you collect notable releases and news, publish them weekly and then summarise everything in monthly releases of Bitcoin Optech. Why are you making exceptions for RGB progress and refusing to follow your own established process?

**Comment by bitschmidty** [comment]
> you collect notable releases and news

(weekly) News from: https://bitcoinops.org/en/internal/sources/

(weekly) Notables from the list we note in the notable section for each newsletter. Currently: "Notable recent changes in Bitcoin Core, Core Lightning, Eclair, LDK, LND, libsecp256k1, Hardware Wallet Interface (HWI), Rust Bitcoin, BTCPay Server, BDK, Bitcoin Improvement Proposals (BIPs), Lightning BOLTs, Lightning BLIPs, Bitcoin Inquisition, and BINANAs."

(monthly) Changes to services and client software: In this monthly feature, we highlight interesting updates to Bitcoin wallets and services.

I noted that the RGB v0.11 Beta 8 changes to the nonce data type and change to data persistence didnt seem notable for this segment last month. Ill continue to keep an eye out for interesting updates here in the future.

> I would kindly ask you to comment on the decision to exclude any mention of RGB, Prime or any other progress from Bitcoin Optech

We have no such exclusion policy.

> were not mentioned even once over the past 2 years

I remember distinctly this large writeup on RGB updates: https://bitcoinops.org/en/newsletters/2023/04/19/#rgb-update
And also have Maxim on the Optech podcast: https://bitcoinops.org/en/podcast/2023/04/20/#rgb-update-transcript
We've covered RGB and related projects several times, as noted in one of your previous periodic interactions on this same topic.

**Comment by UkolovaOlga** [comment]
> (weekly) News from: https://bitcoinops.org/en/internal/sources/
> 
> (weekly) Notables from the list we note in the notable section for each newsletter. Currently: "Notable recent changes in Bitcoin Core, Core Lightning, Eclair, LDK, LND, libsecp256k1, Hardware Wallet Interface (HWI), Rust Bitcoin, BTCPay Server, BDK, Bitcoin Improvement Proposals (BIPs), Lightning BOLTs, Lightning BLIPs, Bitcoin Inquisition, and BINANAs."
> 
> (monthly) Changes to services and client software: In this monthly feature, we highlight interesting updates to Bitcoin wallets and services.

So basically, again, our work (including work on Bitcoin, Lightning and not just on RGB and client-side validation) is out of the scope for any of the topics or reviews above, is not notable for the Topic of client-side validation that is present on your website. Because you do not follow any of our work according to this list https://bitcoinops.org/en/internal/sources/ , you are not adding any of our work to the list of Notables regardless us being there for more than 5 years and building a lot of things (bringing Taproot to rust-bitcoin, building bp library, having RGB smart contracts, writing LNPBPs, building prime, having LNP Node etc) - nothing was notable enough for mentioning, I suppose, or even worth following? And we are not suitable for clients are services because a) RGB is NOT a client and service-related protocol - as I have been trying to tell you but you refuse to read and b) the actual wallets and 'services' improvements we have for some weird reasons also have not been included.

**All mentioned above does, indeed, prove, that you do NOT have an exclusion policy on our work :D** 

> Ill continue to keep an eye out for interesting updates here in the future.

How exactly will you do that  if our work is not on the list of the sources you are following and not on the list of notable things happening in the space?

>I remember distinctly this large writeup on RGB updates: https://bitcoinops.org/en/newsletters/2023/04/19/#rgb-update
And also have Maxim on the Optech podcast: https://bitcoinops.org/en/podcast/2023/04/20/#rgb-update-transcript
We've covered RGB and related projects several times, as noted in one of your previous periodic interactions on this same topic.

Let's be honest here, you did those mentions only after the community forced you to, not because you actually follow our work or think it's valuable or because we did a good job at something. 
Also, we have done MANY releases for the past year and you are still, stubbornly, finding excuses to never add anything about our work neither to the newsletters, nor to the CSV section.

**Comment by bitschmidty** [comment]
> you do NOT have an exclusion policy on our work

That is correct.

> Because you do not follow any of our work according to this list https://bitcoinops.org/en/internal/sources/

These sources are all completely public and nothing is preventing you from posting interesting content there. 

> you did those mentions only after ...

Only after Maxim posted to Bitcoin-dev, one of our sources for the news section that we advised you to post to at that time

> we have done MANY releases for the past year

Please let me know when something that is more interesting than the nonces and backups comes up and Ill consider it for the client/services segment

**Comment by UkolovaOlga** [comment]
> These sources are all completely public and nothing is preventing you from posting interesting content there.

So that you would point me at the door and tell me it's not good enough, as you have been doing here, with RGB updates?

> Only after Maxim posted to Bitcoin-dev, one of our sources for the news section that we advised you to post to at that time

That's not what happened, have some decency.

> Please let me know when something that is more interesting than the nonces and backups comes up and Ill consider it for the client/services segment

Wait a second, so you will follow our work as you wrote above or do I need to notify you when we have updates? You are contradicting your own words (as usual).

>more interesting than the nonces and backups 

This statement is completely false. It proves that  you did absolutely nothing to actually look in the code or release notes for that matter. I also have no idea what you are comparing the release to, especially taking into account that you yourself admitted that you do not follow our work. Sounds like yet another excuse to not ever post anything about our progress.
But of course, there is NO policy to exclude our work from your newsletters :D

**Comment by bitschmidty** [comment]
Ive outlined source materials for each segment of the newsletter. Ill do it here, yet again

(weekly) News from: https://bitcoinops.org/en/internal/sources/

(weekly) Notables from the list we note in the notable section for each newsletter. Currently: "Notable recent changes in Bitcoin Core, Core Lightning, Eclair, LDK, LND, libsecp256k1, Hardware Wallet Interface (HWI), Rust Bitcoin, BTCPay Server, BDK, Bitcoin Improvement Proposals (BIPs), Lightning BOLTs, Lightning BLIPs, Bitcoin Inquisition, and BINANAs."

(monthly) Changes to services and client software: In this monthly feature, we highlight interesting updates to Bitcoin wallets and services.

Im happy to take recommendations for the client/services segment directly, as also already noted. As I am just repeating the same thing here, I think your energy would best spent to get interesting RGB content posted to the public forums.

**Comment by UkolovaOlga** [comment]
> Ive outlined source materials for each segment of the newsletter. Ill do it here, yet again

You are avoiding questions is the worst way possible. Yet again.
 
> Im happy to take recommendations for the client/services segment directly, 

I don't see the reason why a) I should do that because you will again tell me that we don't do enough; and b) yet again (tm) I'm telling you that RGB has nothing to do with the section of clients and services. Please let at least somewhat technical people like @harding that I repeatedly tagged, decide and analyse PRs and issues - clearly you are underqualified to do so.

> I think your energy would best spent to get interesting RGB content posted to the public forums.

Sounds like a good idea as it does seem that Bitcoin Optech is a closed forum putting arbitrary demands to contributors and code, wasting everyone's time, driving contributors away and misleading the community on what's actually happening in the space. Great job, Mike!
