### ISSUE TITLE
Correct address in the newsletter footer? 

### ISSUE THREAD

**Issue by 0xB10C** [bitcoinops/bitcoinops.github.io#191]
>_This issue doesn't actually touch the bitcoinops site itself._ 

The newsletter footer includes:
```
Our mailing address is:
Bitcoin Optech
27 W 24th St Ste 1101
New York, NY 10010-3250
```
Is this address still the correct one or should it be updated to Lex 450?

**Comment by jnewbery** [comment]
I've fixed the template. Next newsletter should have the correct mailing address.

Thanks for reporting this!

**Comment by 0xB10C** [comment]
![Selection_006](https://user-images.githubusercontent.com/19157360/63018126-63316a00-be98-11e9-8a68-44faff7e5632.png)

I just got the newsletter 59 with an empty address in the footer.

**Comment by bitschmidty** [comment]
@0xB10C thanks for the heads up. Ive corrected for this newsletter.
