### ISSUE TITLE
Recap: add transcription line anchor links

### ISSUE THREAD

**Issue by stickies-v** [bitcoinops/bitcoinops.github.io#1976]
It's very convenient that the recap pages (e.g. https://bitcoinops.org/en/podcast/2024/10/01/) have a `Transcription` section. Since they're quite long, I think it would be helpful to add anchor links on a per-line level.

I'm quite unfamiliar with liquid/jekyll, so there are probably better ways to implement this, but something along the lines of this seems like it wouldn't add too much overhead - just updating the recap template?

```
{% capture transcription_lines %}
**Mike Schmidt**: Welcome everyone to Bitcoin Optech Newsletter #322 Recap on Twitter Spaces...

...

**Mike Schmidt**: Thanks guys.
{% endcapture %}

{% assign lines = transcription_lines | split: "\n" %}

{% for line in lines %}
<p id="line{{ forloop.index0 }}">{{ line }}</p>
{% endfor %}
```

If this functionality is desired, I'd be happy to open a pull for it. If someone with more liquid/jekyll chops would like to have a go at this and improve my (untested) suggestion, that would be even better.

**Comment by bitschmidty** [comment]
I think its a good idea. Couple considerations:

@harding is working on a migration to Hugo from Jekyll so we would want to make sure we are not breaking or adding substantial work on that (or add this feature after migration?)

"text fragments" appear to be more widely supported in browsers, for example:
https://bitcoinops.org/en/podcast/2024/10/01/#:~:text=So%2C%20we%20have,over%20the%20years.

https://developer.mozilla.org/en-US/docs/Web/URI/Fragment/Text_fragments#browser_compatibility
This has the benefit of no work and flexibility of selected text beyond just paragraph level. For example, here are two highlights: https://bitcoinops.org/en/podcast/2024/10/01/#:~:text=One%20is%20the%20liquidity%20in%20the%20channel.&text=Then%20there%E2%80%99s%20also%20the%20second%20resource%20that%20can%20be%20exhausted

**Comment by harding** [comment]
I like @bitschmidty's idea of just leaving it to text fragment support in browsers, which is actually using a standardized HTML selector so it should be stable even far into the future.  One of the major challenges in upgrading the site from Jekyll to Hugo was preserving all of our existing anchor links despite slight differences in text-to-url functions, especially across multiple different languages and contexts.

Additionally, something like index-based anchors results in undetectable incorrect linking if we later add or remove lines to a transcript.

**Comment by stickies-v** [comment]
I didn't realize text fragments were a standard, that's cool! In that case, it seems there's little benefit in implementing these anchor links, so I'll close this issue. Thanks for the feedback!

> Additionally, something like index-based anchors results in undetectable incorrect linking if we later add or remove lines to a transcript.

That's true. On the flip side, text fragments may stop working when text is edited in-line (if they're part of the capture group).
