### ISSUE TITLE
compat: Mycelium on Android supports sending to P2WPKH and P2SH

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/bitcoinops.github.io#216]
Reported by @andrewtoth:

> Also it looks like you tested Mycelium for iOS. Their Android wallet is far more popular and better maintained, and I believe it also supports sending to P2WPKH and P2WSH addresses.

**Comment by ksedgwic** [comment]
Mycelium on Android can also generate P2PKH (Legacy), P2SH (Segwit compatible), and Bech32 (Segwit native) addresses.

The matrix is out of date.

**Comment by bitschmidty** [comment]
@ksedgwic Thanks for adding to the discussion. The matrix, I believe, is correct. The testing on Mycelium was on iOS. I believe the matrix information is correct for iOS. 

However, based on feedback it seems Mycelium Android is significantly different and supports more features. It makes sense to have an additional entry for Mycelium on Android. This is in my queue. I will update here when it is tested.

**Comment by Xekyo** [comment]
Oh oops, I didn't realize that Mycelium's Android and iOS implementations were so different, when I updated the segwit compatibility matrix here: https://github.com/bitcoinops/bitcoinops.github.io/pull/510/commits/6657e350a2215bf8fa3c967b64a126d13c9f4d74#diff-0a1e23d669a81c0371ed7b32fdf413c8bb6ca271f3481ca66087a725814562bf

@bitschmidty: Perhaps I should have rather created a separate entry for Android there? Should we still do this: revert the original entry (but label it "iOS"), and add a separate Android entry with the information I collected?
