### ISSUE TITLE
Possible news topic: native segwit outputs doubled this week (why?)

### ISSUE THREAD

**Issue by jonatack** [bitcoinops/bitcoinops.github.io#221]
https://dashboard.bitcoinops.org/d/xVQwtADiz/segwit-usage-trends?refresh=1h&orgId=1

**Comment by harding** [comment]
Interesting!  Saw somebody tweeting the question, so I RT'd it.  Maybe that'll get an answer.

**Comment by ziggamon** [comment]
Found the culprit! 

https://medium.com/@veriblock/veriblock-adopts-segwit-and-will-now-take-more-space-on-bitcoin-edf11fbb6678

For best view of the effect see https://dashboard.bitcoinops.org/d/xVQwtADiz/segwit-usage-trends?refresh=1h&orgId=1&from=1560962879284&to=1568738879285****

**Comment by harding** [comment]
@ziggamon excellent research, even if the results are a bit depressing.  Thanks!

**Comment by jnewbery** [comment]
Thanks for raising this @jonatack and for finding the ~culprit~ cause @ziggamon! We didn't cover this, but please continue to raise issues if you think there's interesting network data that we should cover.
