### ISSUE TITLE
Change wording for PR 15759 merge

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/bitcoinops.github.io#233]
@naumenkogs reports that the last sentence of https://bitcoinops.org/en/newsletters/2019/09/11/#bitcoin-core-15759 ("For details on how an adversary could potentially attack a node in this way, see the TxProbe paper.") is incorrect, since the TxProbe paper is about mapping the topology of the network and not the attacks that an adversary could perform once they know the topology.

I suggest changing the wording of the last sentence to "For details on how an adversary could map the network topology, see the TxProbe paper." What do you think, @naumenkogs?

**Comment by naumenkogs** [comment]
I would clarify by adding something like "by looking at transaction relay", because this would make it more clear why adding these block-relay-only links is robust.

Other than that ACK.

**Comment by jnewbery** [comment]
Fixed in #234. Thanks @naumenkogs !
