### ISSUE TITLE
Add member quotes to web site

### ISSUE THREAD

**Issue by moneyball** [bitcoinops/bitcoinops.github.io#25]
“We're excited to work with Optech on the effort to scale and improve Bitcoin. By collaborating with leading engineers in this space, we'll be able to achieve more than we could have by tackling these problems alone." - Brock Miller, lead Bitcoin Engineer at Coinbase

“We’re proud to be participating in Optech to help further contribute to the crypto community. At Square we continue to explore ways cryptocurrency can expand financial access and we’re excited to help foster a collaborative ecosystem for the benefit of all.” -- Mike Brock, Strategic Development Lead at Square.

**Comment by moneyball** [comment]
"It's great too have a forum to trade ideas about tackling engineering challenges Bitcoin businesses face."

"We appreciate the efforts of Bitcoin Optech to foster communication between Bitcoin companies and the open source community."

- Mark Erhardt, Engineer at BitGo

**Comment by harding** [comment]
@Xekyo is it ok to use that two part quote as a single paragraph in the opposite order?  Also I'd like to add a couple stop words:

> We appreciate the efforts of Bitcoin Optech to foster communication between Bitcoin companies and the open source community.  It's great to have a forum to trade ideas about tackling **the** engineering challenges **that** Bitcoin businesses face.

**Comment by Xekyo** [comment]
@harding: Thanks for asking. Yes, that's fine.

**Comment by jnewbery** [comment]
@moneyball - do you plan to open a PR for this? Where do you think the member quotes should go?

**Comment by moneyball** [comment]
At this point I think the cost outweighs the benefit. The home page is
already a bit noisy/messy and this would just add to that.
