### ISSUE TITLE
Compatibility details for Purse.io and bcoin

### ISSUE THREAD

**Issue by pinheadmz** [bitcoinops/bitcoinops.github.io#295]
bcoin (https://github.com/bcoin-org/bcoin, https://bcoin.io/) is the backend full node and wallet used by Purse.io. They could be listed together or separately (or just one or the other). bcoin offers a range of options, but Purse has been configured with specific settings. I'm happy to make a PR to this repo with details but I'm not sure if the services explicitly need to be tested by an OpTech associate?

Here's the quick details:

SegWit:

- bcoin and Purse support SegWit in all forms: native, nested, send and receive.
- Purse default receive address is bech32 with option for nested.
- Change address type is either legacy or bech32 depending on wallet `witness` setting, Purse always uses bech32 for change.
- bcoin default wallet type is still legacy until https://github.com/bcoin-org/bcoin/pull/827 is merged.

RBF:

- bcoin and Purse reject RBF transactions by default (they do not enter the mempool or wallet until confirmed) meaning they will "show replaced" but not "show original" assuming the replacement is not itself signaling RBF.
- The wallet by default can not send replaceable transactions or replace RBF transactions.
- Mempool replacement for the bcoin full node is in review: https://github.com/bcoin-org/bcoin/pull/811. After merge we'll begin work on adding RBF options to the wallet although RBF will likely remain rejected by Purse, since deposits aren't credited before confirmation anyway.

Screen shots:

Purse -- illustrating bech32 and nested deposit addresses:

![Screen Shot 2019-12-12 at 9 08 56 AM](https://user-images.githubusercontent.com/2084648/70719241-a0c7c780-1cbf-11ea-9743-3900883608ad.png)
![Screen Shot 2019-12-12 at 9 08 17 AM](https://user-images.githubusercontent.com/2084648/70719242-a0c7c780-1cbf-11ea-9832-81da0bdbc817.png)

bcoin -- from our [API docs](http://bcoin.io/api-docs/) illustrating legacy and SegWit wallet account types with receive, change, and nested addresses:

![Screen Shot 2019-12-12 at 9 11 27 AM](https://user-images.githubusercontent.com/2084648/70719340-d10f6600-1cbf-11ea-8084-a5e4535cfae3.png)
![Screen Shot 2019-12-12 at 9 12 08 AM](https://user-images.githubusercontent.com/2084648/70719341-d10f6600-1cbf-11ea-9803-d442b737a39e.png)

**Comment by bitschmidty** [comment]
Hey @pinheadmz ! Thanks for opening this. Would be great to get Purse.io in the matrix. 

It is not required that an "Optech" person execute the testing and open the PR. Although usually as part of review, if its easy enough, I test myself too.

We are considering a "libraries" section for the future potentially, but not yet. So Id recommend a PR for Purse and not bcoin for now.

Let me know if you plan to open the Purse Compatibility Matrix PR.

**Comment by pinheadmz** [comment]
@bitschmidty Thanks dude, opened a PR: https://github.com/bitcoinops/bitcoinops.github.io/pull/303
