### ISSUE TITLE
Travis build error with bundler

### ISSUE THREAD

**Issue by bitschmidty** [bitcoinops/bitcoinops.github.io#306]
Example of failed build:
https://travis-ci.org/bitcoinops/bitcoinops.github.io/builds/628560320?utm_source=github_status&utm_medium=notification

Affecting 

https://github.com/bitcoinops/bitcoinops.github.io/pull/305
and
https://github.com/bitcoinops/bitcoinops.github.io/pull/282

Appears to have started after https://github.com/bitcoinops/bitcoinops.github.io/pull/304 was merged.

**Comment by harding** [comment]
Weird.  #304 said it passed its Travis check.
