### ISSUE TITLE
reduce vertical whitespace between subscribe button and "Member Companies"

### ISSUE THREAD

**Issue by moneyball** [bitcoinops/bitcoinops.github.io#33]
I'm hoping to have some of the company logos be above the fold on a 13" display in order to make the landing page a bit more attention-getting and catchy. There seems to be quite a bit of unnecessary vertical whitespace between the subscribe button and the Member Companies header. I took a quick look at the HTML/CSS and didn't see an obvious way to reduce it.

@harding do you know how?

**Comment by jnewbery** [comment]
Fixed by #56
