### ISSUE TITLE
Get RSS feed to validate

### ISSUE THREAD

**Issue by harding** [bitcoinops/bitcoinops.github.io#350]
Feed does not validate: https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fbitcoinops.org%2Ffeed.xml

After fixing issues, test that it actually loads correctly (and links work) in an RSS feed reader.

**Comment by bitschmidty** [comment]
Looks like in production we are getting a duplicate trailing slash appearing the feed

> https://bitcoinops.org//

Suspect that updating the based hostname to

`url: "https://bitcoinops.org"` in `_config.yml` would do it. Thoughts @harding

**Comment by harding** [comment]
@bitschmidty whoops, sorry.  Your proposed fix sounds reasonable.
