### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by ZeevBB** [bitcoinops/bitcoinops.github.io#444]
Source file: _topics/en/sighash_noinput.md
the link bip-anyprevout at the top of the page is in error

**Comment by bitschmidty** [comment]
Been keeping an eye on this PR: https://github.com/bitcoin/bips/pull/943/
If/when merged, we can use that.

In the meantime, we can leave as is, link to https://github.com/bitcoin/bips/pull/943/ or https://github.com/bitcoin/bips/blob/master/bip-0118.mediawiki  or <something else>.

**Comment by bitschmidty** [comment]
This link is no longer in error, closing.
