### ISSUE TITLE
Use explicit license

### ISSUE THREAD

**Issue by harding** [bitcoinops/bitcoinops.github.io#45]
The homepage says, "all materials and documentation produced are placed in the public domain".  This is fine with me, but my non-lawyer [understanding](https://en.wikipedia.org/wiki/Public_domain#Dedicating_works_to_the_public_domain) is that public domain grants are not valid in all jurisdictions (particularly in the EU), so it's better to use a public domain grant with an explicit backup license like [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

Although CC0 has a no-warranty clause, my (again non-lawyer) interpretation is that it doesn't necessarily apply if the court decides to enforce the public domain grant, possibly opening dedicators to lawsuits for inaccurate documentation.  For that reason, I slightly prefer MIT, which is almost as liberal as public domain but requires the no-warranty statement be retained with all copies.

For comparison, Bitcoin Core, Bitcoin.org, and BitcoinCore.org all use the MIT license for their documentation, and the Bitcoin Wiki uses CC-SA for most content.  My personal preferred license is CC-SA, but I think I'm probably in the minority there in the Bitcoin community and any [FSF-vetted free license](https://www.gnu.org/licenses/license-list.en.html) is ultimately fine by me.

(This issue arose in my mind as I'm about to reuse a couple sentences I wrote for previous newsletters on BitcoinCore.org.)

**Comment by jnewbery** [comment]
Sounds good. I have a slight preference for the MIT licence since I'm more familiar with it. I'll open a PR.
