### ISSUE TITLE
P2TR example is one character too long

### ISSUE THREAD

**Issue by Xekyo** [bitcoinops/bitcoinops.github.io#498]
I was reading the [Taproot overview in Newsletter 46](https://bitcoinops.org/en/newsletters/2019/05/14/#overview-of-the-taproot--tapscript-proposed-bips). I've noticed that the Taproot address example there has one character more than the P2WSH address example. Per the latest address encoding proposal, P2TR and P2WSH addresses should be the same length.

Do we update that sort of information for past newsletters or do we leave it, because it was correct at the time the newsletter was published?

**Comment by jnewbery** [comment]
I don't think we'd change details if they were correct at the time of publication. At most, we could add a note saying that the proposal has changed subsequently, but I don't think it's worth it. We cover lots of proposals that are in flux. It's not sustainable to go back and add notes to all old newsletters as proposals mature.

**Comment by harding** [comment]
Agree with @jnewbery.  The date of the newsletter is part of both the URL and the visible page header, so I think it's ok for the content itself to become dated.  If anyone's really concerned about this, we can optionally put a small persistent banner across either the top or bottom of the page on all newsletters older than a few months reminding readers that the content may be out of date.
