### ISSUE TITLE
Heads up electrs 0.8.8 was released

### ISSUE THREAD

**Issue by Kixunil** [bitcoinops/bitcoinops.github.io#522]
This wasn't mentioned in previous newsletter, wanted to alert you but got drowned in other things. Not a big deal. It seems like you already mentioned `electrs` so I assume it's interesting for newsletter. This release contains a deprecation and it updates some vulnerable dependencies (the impact on `electrs` itself is unknown) so I think it's worth a bit more publicity.

**Comment by bitschmidty** [comment]
Martin, thanks for the heads up. Ill give it a look for next month's client services section. Cheers.

**Comment by bitschmidty** [comment]
@Kixunil Looking through the commits, I did not think the changes were substantial enough for the writeup this month. But I did add the electrs repo to my watch list each month!

**Comment by Kixunil** [comment]
Note that there was 0.8.9 release since I posted this. Could it be that it confused you?

Either way, I'm myself not sure what should be considered substantial. I don't mind you skipping, just making sure everything is clear.
