### ISSUE TITLE
Add linter to catch common typos

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/bitcoinops.github.io#641]
There are certain typos/style guide violations that we often make, eg:

- PBST for PSBT (#640)
- blockchain for block chain

It'd be helpful to add a linter to catch these.

**Comment by harding** [comment]
The BOLTs repo has a wrapper around aspell for spellchecking everything, with a custom whitelist for specialized compsci/Bitcoin/LN vocabulary.  I think that would take too much work in our case (e.g. almost every newsletter of ours includes people's names that aren't in my system dictionary).  However, it may be worth looking into using aspell with a custom dictionary that works as a blacklist.
