### ISSUE TITLE
Website occasionally fails to load

### ISSUE THREAD

**Issue by jnewbery** [bitcoinops/bitcoinops.github.io#7]
```
This page isn't working
bitcoinops.org redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS
```

**Comment by moneyball** [comment]
I just saw this problem again on Chrome/MacOS, so I do worry this is frequent enough and probably affects many/most/all users to warrant prioritizing it. What debugging information can I collect to help?

As for reproducibility on your end, my recommendation would be to excessively load the web page throughout the day like I do :)

**Comment by jnewbery** [comment]
If you're able to reproduce this, can you try loading the page with the 'Network' tab of Chrome's developer tools open, and see what redirects you're getting? I just get:

-  a 200 response when I navigate to `bitcoinops.org`
- a 301 redirect to `bitcoinops.org` when I navigate to `www.bitcoinops.org`

(which is what I would expect).

**Comment by moneyball** [comment]
I'm not sure how or where to access a log file (I did check "preserve log"). But here is a screenshot.
<img width="1365" alt="screen shot 2018-06-28 at 9 14 07 am" src="https://user-images.githubusercontent.com/326147/42046920-c7e8c684-7ab3-11e8-9824-121644d07663.png">

**Comment by moneyball** [comment]
Here is perhaps a better view, as I cleared the log and refreshed the page, so this represents a single attempted page load.
<img width="1426" alt="screen shot 2018-06-28 at 9 16 18 am" src="https://user-images.githubusercontent.com/326147/42047018-005ebd20-7ab4-11e8-8819-1263df87531c.png">

**Comment by jnewbery** [comment]
I think I've fixed the DNS config that was causing this redirect loop.

@moneyball - please continue to monitor. I've only been able to repro this once (before updating the DNS config).

**Comment by jnewbery** [comment]
Seems to be fixed. Closing for now.

@moneyball - please reopen if you see this issue again.
