### ISSUE TITLE
sharing content from the newsletter on bitcointechweekly.com

### ISSUE THREAD

**Issue by sp4ke** [bitcoinops/bitcoinops.github.io#70]
Hi, first thanks for your efforts maintaining this newsletter. I started BitcoinTechWeekly.com magazine around a year ago to cover all technological progress in bitcoin excluding the price, ico and speculation talk. 

I would like to reuse parts of your newsletter on my weekly issues especially the `notable commits`. Would you guys mind if I did it providing I attribute this work to you of course ? I am not sure how does this work regarding the LICENSE part. I am currently releasing all content under [CC BY SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)

**Comment by moneyball** [comment]
Thank you for reaching out to ask us about this. It is ok for you to use the notable commits from our newsletter. You should change the wording from "contributed by Bitcoin Optech" to "originally published by Bitcoin Optech in newsletter #x" with a link to the individual newsletter. Also, it is important that you do not copy content from us until after we've published it. There are often errors and poorly worded content while still in the review process, so please wait until after we publish.
