### ISSUE TITLE
Add Bitnob wallet to compatibility matrix

### ISSUE THREAD

**Issue by Blazing-Mike** [bitcoinops/bitcoinops.github.io#760]
[Bitnob](https://bitnob.com/) is a custodial wallet that allows you Buy, sell, borrow, earn, send, receive, and pay with Bitcoin in minutes. It was built in Africa. Opening this issue to add it to the compatibility matrix, i am working on the PR too.

**Comment by Xekyo** [comment]
Cool, thanks for letting us know. Looking forward to your PR.
